---
name: Build and deploy images
on:
  schedule:
    # rebuild every Thursday at 9:24 UTC
    - cron: "24 9 * * 3"
  push:
    branches:
      - main
      - master
      - feature/**
      - bugfix/**
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  build-images:
    name: Build Docker images
    runs-on: ubuntu-latest
    env:
      image: ghcr.io/seravo/flask
    steps:
      - id: clone-repository
        uses: actions/checkout@v2
        name: Clone git repository

      - id: docker-login
        uses: Seravo/actions/docker-login@v0.11
        name: Login to ghcr.io

      # To speed up builds, try to use previously built image as cache source.
      # However, skip this if we're running weekly scheduled build to ensure
      # that we get latest APT versions at least once a week
      - if: ${{ github.event_name != 'schedule' }}
        name: Pull previously built image
        id: docker-pull
        uses: Seravo/actions/docker-pull@v0.11
        with:
          image: "${{ env.image }}"

      - if: ${{ github.event_name != 'schedule' }}
        name: Pull previously built image by commit id
        id: docker-pull-commit
        uses: Seravo/actions/docker-pull@v0.11
        with:
          image: "${{ env.image }}:${{ github.sha }}"
        continue-on-error: true

      - id: docker-build
        uses: Seravo/actions/docker-build@v0.11
        name: Build image
        with:
          image: "${{ env.image }}"

      - id: run-test-image
        name: Run new image
        run: docker run --rm -d -e FLASK_APP=hello:app -v $(pwd)/app:/app -p 127.0.0.1:8080:8080 --name flask "${{ env.image }}"

      - id: run-test
        name: Run tests against the image
        run: curl -iLsS http://127.0.0.1:8080/

      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Push new image to production
        id: docker-push-master
        uses: Seravo/actions/docker-push@v0.11
        with:
          image: "${{ env.image }}"

      - id: refname
        name: Convert git refname to valid Docker tag
        run: echo "::set-output name=refname::$(echo "${{ github.ref_name }}" |sed 's/\//-/g')"

      - id: docker-tag
        name: Tag image with run id
        uses: Seravo/actions/docker-tag@v0.11
        with:
          source: "${{ env.image }}"
          target: "${{ env.image }}:${{ steps.refname.outputs.refname }}"

      - id: docker-push
        name: Push image with run id
        uses: Seravo/actions/docker-push@v0.11
        with:
          image: "${{ env.image }}:${{ steps.refname.outputs.refname }}"
